version: "3.9"
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '54320:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
