version: "3.9"
services:
  nginx:
    build:
      context: .docker/dev/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./.docker/dev/nginx/logs:/var/log/nginx
    ports:
      - 3030:80

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '54320:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
